version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres1234
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/login_crud
    ports:
      - "3000:3000"
    depends_on:
      - db
